name: Initial workflow for linting
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Read the code
        uses: actions/checkout@v4
      - name: Setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules_dependencies_${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
